### ISSUE TITLE
azcopy brakes while read line pipe

### ISSUE THREAD

**Issue by andrei-muresanu** [Azure/azure-storage-azcopy#974]
##### Note: The version is visible when running AzCopy without any argument
10.3.4
### Which platform are you using? (ex: Windows, Mac, Linux)
rhel 6.10
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

grep "string" file | while read line; do azcopy copy "${line}"; done

### What problem was encountered?

even if there are multiple lines in the file (like complete urls), only the first line is processed. next read line just returns (as if the pipe is empty). no error whatsoever and couldn't figure out till now why that may be. The pipe:[x] file descriptor is still available

Example from /proc/pid/fd of the script containing the azcopy:

dr-x------ 2 root root  0 Apr 22 18:33 .
dr-xr-xr-x 8 root root  0 Apr 22 18:33 ..
lr-x------ 1 root root 64 Apr 22 18:35 0 -> pipe:[165068451]
l-wx------ 1 root root 64 Apr 22 18:35 1 -> file.log
l-wx------ 1 root root 64 Apr 22 18:35 2 -> file.log

lsof lists the pipe (a sleep 5000 was put right after as to be able to debug). Script running as cron job.

bash      27276      root    0r     FIFO                0,8       0t0  165068451 pipe
sleep     27329      root    0r     FIFO                0,8       0t0  165068451 pipe

My guess is that it's related to azcopy being able to write content to blob storage from pipe (must be doing something with stdin).

### How can we reproduce the problem in the simplest way?

create a file named file with multiple lines like:
testfile1 https://.....

and run the above command

### Have you found a mitigation/solution?

force an empty stdin to azcopy:

: | azcopy whatever

(thanks @stewartadam for the obvious workaround)

**Comment by andrei-muresanu** [comment]
looks like the second usage bellow (azcopy cp --help excerpt) doesn't check if file parameter is passed to azcopy. I expect in my scenario it also corrupts the resulting files - puts the content of the pipe in the first and therefore the pipe gets consumed.

Upload a single file by using a SAS token:

  - azcopy cp "/path/to/file.txt" "https://[account].blob.core.windows.net/[container]/[path/to/blob]?[SAS]"

Upload a single file by using a SAS token and piping (block blobs only):

  - cat "/path/to/file.txt" | azcopy cp "https://[account].blob.core.windows.net/[container]/[path/to/blob]?[SAS]"

**Comment by JohnRusk** [comment]
I haven't quite understood what you're aiming to do here, sorry. What is in your text file, is it a set of pairs of (local filename, remote URL)?

**Comment by andrei-muresanu** [comment]
it doesn't matter what is in the text file (except for context and syntax purposes). Let's say something like this (simplified) - on each line:

string2 sometext
string1 /tmp/file1 https://storageaccount1.blob.core.windows.net/container1/file1?[SAS]
string1 /tmp/file1 https://storageaccount2.blob.core.windows.net/container1/file1?[SAS]
string1 /tmp/file1 https://storageaccount3.blob.core.windows.net/container1/file1?[SAS]
...
string1 /tmp/file1 https://storageaccountn.blob.core.windows.net/container1/file1?[SAS]
string2 someother text

Basicaly copy the same file to multiple storage accounts using a while read loop in something like the following (the actual logic is a bit more complex but same idea):

grep "string1" file | awk '{$1=""; print $0}' | while read line; do azcopy copy "${line}"; done

**Comment by JohnRusk** [comment]
So you have essentially a set of lines, where each line is a set of parameters to AzCopy?  In that case, the first thing I'd suggest you check is whether azcopy thinks its getting one parameter or many? (You want many, right - at least 2, source and dest?)  To check that, I'd add at bogus switch to the end of your line, like --this-does-not-exist.  If AzCopy fails and says that not a valid command line option, then it is getting separate parameters. If it doesn't, then I'd suspect that its getting all the params in such a way that it things there's only one parameter (which happens to have spaces in it).

Oh, one thing that might be important: what you're trying to do looks a bit similar to something that we already provide native support for.  Have a look at this, and see if it suits: https://github.com/Azure/azure-storage-azcopy/wiki/Listing-specific-files-to-transfer

**Comment by andrei-muresanu** [comment]
it can't think that it's getting only one parameter as it copies the first file (disregard the " as it was plaed ad-hoc as an example).

The functionality mentioned does not allow copying to multiple blob stores the same file from what i saw.

It should be easily reproducible ;)

**Comment by JohnRusk** [comment]
We don't have time to reproduce this this week, sorry @andrei-muresanu.  

BTW, it doesn't yet sound like an actual AzCopy bug. It still sounds like something about the way your script is invoking it (although I don't know exactly what the issue might be).

**Comment by stewartadam** [comment]
I believe this **is** an azcopy bug, I can easily reproduce. Mention above is correct, azcopy appears to be manipulating stdin and exhausting pipes that don't belong to it, causing bash to terminate its loop prematurely.

Workaround is to force an empty stdin to azcopy:
```bash
: | azcopy whatever
```

Example repro: since azcopy doesn't support more than once source argument, one must call azcopy multiple times if the files are in different directories (or if those directories contain more than the specific files to be uploaded):
```bash
find repo_path -name '*.pdf | while read line;do
  azcopy "$line" https://dst-uri-with-sas
```

Only a single file is uploaded. If you swap to any other command, e.g. echo, the loop proceeds as usual:
```bash
find repo_path -name '*.pdf | while read line;do
  echo azcopy "$line" https://dst-uri-with-sas
```

**Comment by JohnRusk** [comment]
IIRC, it is only supposed to read stdin if it thinks its in pipe mode (i.e. if it thinks you did not pass it a source and a destination, but only passed it one).  I'm wondering if we need to change it so that pipe mode can only in invoked if you supply some kind of parameter to explicitly opt in to that mode.

**Comment by stewartadam** [comment]
Linux convention for some commands is to use a single dash instead of the source parameter as a mark to use stdin which could be adopted, but I’m curious why azcopy would think it needs to be in stdin mode here - it definitely was passed a src and dst argument...

**Comment by JohnRusk** [comment]
I'm curious about the same thing, and I don't know the answer.

**Comment by mk-pradeep** [comment]
Even i am facing the same issue with azcopy command with while loop by reading the text file where i am trying to copy the files  to multiple blob stores. It reads the first line and copy to the blob and terminates. However just with the echo loop it works fine. Any workaround for this problem.

**Comment by HMatsumura** [comment]
I'm also encountering this issue. If use `while read line` loop, it doesn't hit second loop. (It occurs only if the processing in the loop is `azcopy`.) On the other hand, if use `for` loop, we can success even after second loop.

e.g.) cat /tmp/uploadfile.txt
file1
file2

Fail case: (only run for "file1")
```
while read line  
do  
  azcopy copy "/tmp/$line" "blob_path"  
done < /tmp/uploadfile.txt
```

Success case: (run for "file1" and "file2")
```
for line in `cat /tmp/uploadfile.txt`
do  
  azcopy copy "/tmp/$line" "blob_path"  
done
```

This issue has not resolved yet in the latest v10.5.0. Has the design changed that we cannot use "while read line" loop after v10.3.4?
@JohnRusk, would you know the plan this issue will be resolved?

**Comment by JohnRusk** [comment]
attn @adreed-msft or @zezha-msft

**Comment by stewartadam** [comment]
@adreed-msft or @zezha-msft still an issue with 10.6.0.

If it helps narrow down the code path, it does not happen when no destination is provided:
```
$ echo -e "one\ntwo\nthree" | while read line;do azcopy copy $i; done
INFO: The parameters you supplied were Source: '~pipe~' of type Pipe, and Destination: '5' of type Local
... # error output repeated three times
```

But when a bogus http destination is provided, it kills the loop:
```
$ echo -e "one\ntwo\nthree" | while read line;do azcopy copy $i https://foo; done
INFO: The parameters you supplied were Source: '5' of type Local, and Destination: 'https://foo' of type Local
... # error output only happens once
```

**Comment by mohsha-msft** [comment]
@andrei-muresanu ,

We've fixed std. pipe related flows in the recent releases. Please take a look once. Reach out if the issue persists?

**Comment by stewartadam** [comment]
Confirmed working, thanks!

**Comment by sailepradh** [comment]
> I'm also encountering this issue. If use `while read line` loop, it doesn't hit second loop. (It occurs only if the processing in the loop is `azcopy`.) On the other hand, if use `for` loop, we can success even after second loop.
> 
> e.g.) cat /tmp/uploadfile.txt
> file1
> file2
> 
> Fail case: (only run for "file1")
> 
> ```
> while read line  
> do  
>   azcopy copy "/tmp/$line" "blob_path"  
> done < /tmp/uploadfile.txt
> ```
> 
> Success case: (run for "file1" and "file2")
> 
> ```
> for line in `cat /tmp/uploadfile.txt`
> do  
>   azcopy copy "/tmp/$line" "blob_path"  
> done
> ```
> 
> This issue has not resolved yet in the latest v10.5.0. Has the design changed that we cannot use "while read line" loop after v10.3.4?
> @JohnRusk, would you know the plan this issue will be resolved

I too am facing the issue. Do you know how I can resolve it ?

**Comment by stewartadam** [comment]
@sailpradh per above, have you tried with the latest azcopy version?

**Comment by sailepradh** [comment]
@stewartadam I am using the latest version of azcopy( v10.10.0) in ubuntu (v20.04) version. I solved the problem rather using the for loop rather than the for loop .

**Comment by jibonilla03** [comment]
I am having the same problem on newest version # azcopy --version
azcopy version 10.11.0 

find ${BACKUPS_PATH} -type f -mmin ${BACKUPS_AGE} -print0 |
  while IFS= read -r -d $'\0' file; do
    azcopy copy  "${file}" "${AZURE_STORAGE_ACCOUNT}${BACKUPS_CONTAINER}/${file#${BACKUPS_PATH}}" --put-md5 --log-level=ERROR
  done

Please reopened this issue!

**Comment by aknagy** [comment]
Please reopen the issue. For now I could use a workaround, but the issue exists.

**Comment by jgmarcel** [comment]
I am also facing this issue with azcopy version 10.11.0.

**Comment by zezha-msft** [comment]
@siminsavani-msft could you please take a look? It seems that the issue is not fully resolved (I haven't tried a repro). Please try the examples listed [here](https://github.com/Azure/azure-storage-azcopy/issues/974#issuecomment-659160273).

**Comment by mjpost** [comment]
This issue still exists with azcopy 10.13.0. I just burned nearly two hours trying to debug why my perfectly normal loop would only run the first instance. I thought I was going insane until a colleague pointed me here. Here are instructions for repeating this:

In file `urls.txt`
```text
url1
url2
...
```

Then

```bash
while read url; do
    azcopy cp $url .
done < urls.txt
```

This will only download the first URL, and then will quit the loop. Putting `echo` in front of `azcopy` causes everything to work just fine.

I don't know if this is due to a philosophical difference between Windows / UNIX software, but IMHO, `azcopy` has no business touching STDIN. This really breaks the UNIX mindset and is extremely difficult to debug.

**Comment by mjpost** [comment]
FTR, my workaround is this, but it remains that this was a deeply mysterious bug:

```bash
for lineno in $(seq 1 $(cat urls.txt | wc -l)); do
    url=$(lines $lineno urls.txt)
    azcopy cp $url .
done
```

where [lines](https://github.com/mjpost/bin/blob/master/lines) fetches line `N` from a file.

**Comment by mrsabapathy** [comment]
Try to use read -u option (file descriptor). 

@andrei-muresanu 
while read -u10 line; do azcopy copy "${line}"; done 10< <(grep "string1" file | awk '{$1=""; print $0}' )

@mjpost
while read -u10 url; do
    azcopy cp $url .
done 10< urls.txt

**Comment by zezha-msft** [comment]
@adreed-msft to take a look

**Comment by jon-gr** [comment]
This issue still is present with azcopy version 10.17.0
The while loop (as described above) fails out of the while loop on the first try, after successfully copying the  first file from the list.
The @andrei-muresanu fd method is a valid workaround.
To summarize, where urls.txt contains a list of urls on each line.....

This fails:   [drops out of the while loop after 1st file]
while read -r url; do
    azcopy cp $url .
done < urls.txt

This works:
while read -u10 url; do
    azcopy cp $url .
done 10< urls.txt

**Comment by hfujisawaCA** [comment]
I am glad I found this forum. I also use azcopy in the loop scenario where I have to copy log files from network devices in S3. I was very confused why azcopy quits at the first iteration. 

@mrsabapathy thank you for your suggestion!

**Comment by mstenz** [comment]
we have the same issue with "while read". changed to for loop now to hope it doesn't occur.

**Comment by mjpost** [comment]
I would reiterate that this issue has cost lots of people hours of time. The issue is not at all expected or discoverable and really should be addressed.

**Comment by fasseg** [comment]
Also seeing this issue with version 10.18.1:
```
while IFS= read -r line;do
    for path in $line;do
        bash -c 'azcopy cp --dry-run "$1" "$2"' bash "${AZURE_STORAGE_URL}${path}?${AZURE_SAS_TOKEN}" "/tmp"
    done
done <<< $paths
```
azcopy seems to consume stdin and reads the whole `$paths` variable. Then it reports a lot of errors saying: `INFO: Discarding incorrectly formatted input message`. 
After that `read -r line` of course reports no more input on the second iteration and the loop is finished after a single pass.

**Comment by stewartadam** [comment]
@zezha-msft any updates?

**Comment by JohnRusk** [comment]
@adreed-msft ^ in case you're not auto notified

**Comment by chloeyin** [comment]
Have the same problem

**Comment by bramvdklinkenberg** [comment]
Same issue as @fasseg describes

**Comment by theGOTOguy** [comment]
We're also having this issue.  In our case, all files that need to be processed are too big to fit on the disk.  Therefore, we need to process them one at a time and upload the result in a bash `for` loop, removing the files after each step.

I used the following workaround.

If you have this pattern, which will be affected by this bug:
```bash
cat files_list | while read source 
do
  azcopy cp $source .
done
```

Replace it with:
```bash
cat files_list | while read source 
do
  echo cp $source . | xargs azcopy
done
```

Then your `azcopy` command should work like you expect.

**Comment by msimp2** [comment]
> This issue still is present with azcopy version 10.17.0 The while loop (as described above) fails out of the while loop on the first try, after successfully copying the first file from the list. The @mrsabapathy fd method is a valid workaround. To summarize, where urls.txt contains a list of urls on each line.....
> 
> This fails: [drops out of the while loop after 1st file] `while read -r url; do azcopy cp $url . done < urls.txt ` This works: `while read -u10 url; do azcopy cp $url . done 10< urls.txt`

This is the only thing that seems to have worked for me.

**Comment by Arjun-Siva** [comment]
The copying can be done asynchronously

```
while IFS= read -r filename || [ -n "$filename" ]; do
        # Download the file using azcopy in the background
        azcopy copy "${url}/${filename}" "${local_directory}" &
done < "$file_path"

# Wait for background processes to finish
wait

echo "Done"
```

**Comment by mjpost** [comment]
These are good workarounds, and fast, but they don't address the underlying problem that `azcopy` should not silently consume STDIN, because this breaks the standard UNIX API in a way that is not discoverable.

**Comment by xuyuji9000** [comment]
I failed with the following `azcopy copy` while loop attempt.

``` shell
while read -r remote_url ;
do
    azcopy copy $remote_url ./ --recursive
done <<EndOfMessage
first_url
second_url
EndOfMessage
```

And the following response helped with the situation.

> Try to use read -u option (file descriptor).
> 
> @andrei-muresanu while read -u10 line; do azcopy copy "${line}"; done 10< <(grep "string1" file | awk '{$1=""; print $0}' )
> 
> @mjpost while read -u10 url; do azcopy cp $url . done 10< urls.txt

**Comment by mjpost** [comment]
Yes, there are workarounds if you adjust the loop. The point is that you have to _know_ to use these workarounds in the first place, because `azcopy` consumes STDIN in the first place, which it has no business doing, since it breaks the expected behavior in a mysterious, hard-to-discover manner.

**Comment by slagelwa** [comment]
I've reported similar stdin issues in #2510 and #2689

**Comment by dphulkar-msft** [comment]
We recommend trying the latest version of Azcopy (10.28.1) to see if it resolves the issue. We will go ahead and close the ticket for now. Please feel free to reopen it if you continue to experience the issue after updating to the latest version.

Thank you for your patience!

**Comment by stewartadam** [comment]
@dphulkar-msft I understand that open-source issue management can be challenging but closing this issue feels a bit dismissive when users have already posted a clear repro for the issue and been posted that it continues to affect azcopy for **four years**.

A basic bash pipe-loop should be included in the CI tests that would catch this right away.

Re-opening as #3024.
